config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  resources :users do
    member do
      get 'p5'
      get 'delete_p5'
      resources :rewards    
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reward_history.rb
class RewardHistory < ApplicationRecord
	belongs_to :user, optional: true
	validates_presence_of :points
end

app/models/user.rb
class User < ApplicationRecord
	has_many :reward_histories, foreign_key: 'given_by'
	validates_presence_of :name
	accepts_nested_attributes_for :reward_histories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
	before_action :find_user, only: [:index, :new, :create]

	def index
		@reward_histories = @user.reward_histories
	end

	def new
		@reward_histories = @user.reward_histories
		@p5_balance = 100 - @reward_histories.pluck(:points).sum
		@reward_history = @reward_histories.new
		@users = User.where.not(id: @user.id).order('name asc')
	end

	def create
		@reward_history = @user.reward_histories.new(given_to: params[:given_to], points: params[:points])
		@reward_history.save
	end

	private

	def find_user
		@user = User.find_by(id: params[:id])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :find_user, only: [:show, :edit, :update, :p5, :delete_p5, :rewards]
	before_action :find_reward_histories, only: [:p5, :rewards]

	def index
		@users = User.all.order('name asc')
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to users_path
		else
			@errors = @user.errors
			render :new, status: :unprocessable_entity
		end
	end

	def update
	  if @user.update(user_params)
	    redirect_to users_path
	  else
	  	@errors = @user.errors
	    render :edit, status: :unprocessable_entity
	  end
	end

	def p5
		
	end

	def delete_p5
		RewardHistory.find_by(id: params[:id]).destroy
		redirect_to p5_user_path(@user)
	end

	def rewards
	end

	private

	def user_params
		params.require(:user).permit(:name)
	end

	def find_user
		@user = User.find_by(id: params[:id])
	end

	def find_reward_histories
		@reward_histories = @user.reward_histories
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Mini Peerfive" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rewards/index.html.erb
<h4>Rewards Balance</h4>
<table>
  <thead>
    <tr>
      <td>S.no</td>
      <td>Datetime</td>
      <td>Rewards Received</td>
      <td>User Name</td>
    </tr>
  </thead>
  <tbody>
    <%@reward_histories.each_with_index do |reward_history, index|%>
      <tr>
        <td><%= index + 1%></td>
        <td><%= reward_history.created_at.in_time_zone("Chennai").strftime("%I:%M %P")%></td>
        <td><%= reward_history.points%></td>
        <td><%= User.find_by(id: reward_history.given_by).name%></td>
      </tr>
    <%end%>
  </tbody>
</table>
<br/>
<%= link_to 'New Reward', new_reward_path(@user) %>

app/views/rewards/new.html.erb
<%= form_with(url: rewards_path) do |form| %>
  <div>
    <%= form.label :user %><br>
    <%= form.collection_select :given_to, @users, :id, :name, prompt: true%>
  </div>
  <br/>
  <div>
    <%= form.label :points %><br>
    <%= form.number_field :points, in: 1..100%>
  </div>
  <div>
    <p>Left P5 Balance - <%= @p5_balance%></p>
  </div>
  <br/>
  <div>
    <%= form.submit 'Submit'%>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with model: user do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% user.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <br/>
  <div>
    <%= form.submit 'Submit'%>
    <%= button_to "Cancel", users_path, method: :get%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render "form", user: @user %>

app/views/users/index.html.erb
<h1>Users</h1>
<table>
  <thead>
    <tr>
      <td>S.no</td>
      <td>Name</td>
      <td>P5 balance</td>
      <td>Reward balance</td>
      <td>Manage</td>
    </tr>
  </thead>
  <tbody>
    <%@users.each_with_index do |user, index|%>
      <tr>
        <td><%=index + 1%></td>
        <td><%= user.name%></td>
        <td><%= user.name%></td>
        <td><%= user.name%></td>
        <td><%= link_to "Edit", edit_user_path(user)%> <%= link_to 'Show', user%></td>
      </tr>
    <%end%>
  </tbody>
</table>
<br/>
<%= link_to "New User", new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render "form", user: @user %>

app/views/users/p5.html.erb
<h4>P5 Balance</h4>
<table>
  <thead>
    <tr>
      <td>S.no</td>
      <td>Datetime</td>
      <td>P5 given</td>
      <td>User Name</td>
      <td>Delete</td>
    </tr>
  </thead>
  <tbody>
    <%@reward_histories.each_with_index do |reward_history, index|%>
      <tr>
        <td><%= index + 1%></td>
        <td><%= reward_history.created_at.in_time_zone("Chennai").strftime("%I:%M %P")%></td>
        <td><%= reward_history.points%></td>
        <td><%= User.find_by(id: reward_history.given_to).name%></td>
        <td><%= link_to "Delete", delete_p5_user_path(reward_history), method: :delete%></td>
      </tr>
    <%end%>
  </tbody>
</table>
<br/>
<%= link_to 'New Reward', new_reward_path(@user) %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<%= link_to 'Edit', edit_user_path(@user) %>
<%= link_to 'p5', p5_user_path(@user) %>
<%= link_to 'rewards', rewards_path(@user) %>
<%= link_to 'Back', users_path %>